chore/task-1-KAN-9-setup-done
KelliaKamikazi/Certificate-Manager---Kellia pull request #1
Opened 2024-07-09 15:01 UTC by KelliaKamikazi

#### The setup of the project 
- I have setup my project using react with no other library.
- Below we have a screenshot of the structure and the first compiled  html file output.

#### Ticket / Jira Link
- [[KAN-##](https://task-force-pro-dccs.atlassian.net/jira/software/projects/KAN/boards/1?assignee=712020%3Ab9bb79c7-4352-4d17-9af2-5c36278b1670&selectedIssue=KAN-)](https://task-force-pro-dccs.atlassian.net/browse/KAN-6)

#### Screenshots:

<img width="382" alt="Screenshot 2024-07-09 at 16 53 31" src="https://github.com/KelliaKamikazi/Certificate-Manager---Kellia/assets/115183307/00511bf1-51ff-4fc8-a803-d4f62de4b509">

<img width="1680" alt="Screenshot 2024-07-09 at 16 52 06" src="https://github.com/KelliaKamikazi/Certificate-Manager---Kellia/assets/115183307/a4c6e6bc-5179-4216-a629-7a1f36a7954f">

2024-07-10 10:20 UTC, Inclet requested changes
Thank you for your work . You've made a good start, but there are several areas where we can improve the project structure, configuration, and code quality.

## Strengths
- Basic React and TypeScript setup in place
- Webpack configuration included for building the project
- Use of important plugins like HtmlWebpackPlugin and CleanWebpackPlugin

## Areas for Improvement

1. **Project Structure**
   - [ ] Remove the inner `certificate-manager` folder. Keep its contents, but move them to the root of your project.
   - [ ] Organize your files into appropriate directories (e.g., `src/components`, `src/styles`, etc.)

2. **Package.json**
   - [ ] Update dependencies to stable versions
   - [ ] Add scripts for development, production builds, and type checking
   - [ ] Include more project metadata (description, repository, etc.)

3. **Webpack Configuration**
   - [ ] Separate development and production configurations
   - [ ] Improve module rules for better handling of different file types
   - [ ] Implement better caching strategies and optimizations

4. **React Code**
   - [ ] Update to use modern React 18 APIs (e.g., `createRoot`)
   - [ ] Implement proper type checking and null safety
   - [ ] Consider using React.StrictMode

5. **TypeScript Integration**
   - [ ] Ensure proper TypeScript configuration
   - [ ] Use TypeScript-aware loaders and plugins in Webpack

6. **Development Experience**
   - [ ] Set up proper source map handling for better debugging
   - [ ] Implement hot module replacement for faster development

7. **Pull Request Practices**
   - [ ] Remove screenshots of code from PR descriptions. Code should be directly reviewable in the PR.
   - [ ] Use screenshots only for demonstrating UI changes or features.

## Key Recommendations

1. Restructure your project to remove the nested `certificate-manager` folder.
2. Update your `package.json` with correct versions and additional scripts.
3. Refactor your Webpack config to address the issues mentioned.
4. Update your React code to use current best practices and APIs.
5. Ensure your TypeScript configuration is optimized for your project needs.
6. Implement proper error handling and logging.
7. For future PRs, include code directly rather than as screenshots. Reserve screenshots for UI demonstrations only.

## Next Steps

1. Address the structural issues by reorganizing your project files.
2. Update your configurations based on the feedback provided for `package.json` and `webpack.config.js`.
3. Refactor your React code entry point as suggested.
4. Review and update any other React components in your project to follow best practices.
5. Ensure all TypeScript files are properly typed.
6. Test your development and build processes to ensure everything works as expected after making these changes.

Your project shows promise, but needs some refinement to align with current best practices and to optimize for both development and production environments. These changes will significantly improve your project's maintainability, performance, and developer experience.

Please feel free to ask if you need any clarification or assistance in implementing these suggestions.

2024-07-10 10:20 UTC, Inclet commented on certificate-manager/package.json
Thank you for sharing your `package.json` file. It's a good start for a React project with TypeScript and Webpack. Here are some observations and suggestions for improvement:

#### Strengths
- Good separation of dependencies and devDependencies
- Includes essential React, TypeScript, and Webpack packages
- Basic npm scripts for starting and building the project

#### Suggestions for Improvement

1. **Project Metadata**
   - Add a meaningful description to the "description" field
   - Consider adding a "repository" field with your project's repository URL

2. **Scripts**
   - Add a `"dev"` script for development mode (e.g., `"dev": "webpack serve --mode development"`)
   - Modify the `"build"` script to use production mode (e.g., `"build": "webpack --mode production"`)
   - Add a `"type-check"` script to run TypeScript compiler (e.g., `"type-check": "tsc --noEmit"`)

3. **Dependencies**
   - Consider adding `@types/node` as a devDependency for Node.js types

4. **Versioning**
   - Use exact versions for dependencies to ensure consistency (remove `^`)

5. **Package Versions**
   - Some package versions seem to be ahead of the latest stable releases (e.g., react@18.3.1). Double-check if these are the versions you intend to use.

#### Revised package.json

```json
{
  "name": "certificate-manager",
  "version": "1.0.0",
  "description": "A certificate management application built with React and TypeScript",
  "main": "index.js",
  "scripts": {
    "start": "webpack serve --open",
    "dev": "webpack serve --mode development",
    "build": "webpack --mode production",
    "type-check": "tsc --noEmit",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": ["certificate", "management", "react", "typescript"],
  "author": "Your Name",
  "license": "ISC",
  "repository": {
    "type": "git",
    "url": "https://github.com/yourusername/certificate-manager.git"
  },
  "dependencies": {
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "@babel/core": "7.23.7",
    "@babel/preset-env": "7.23.7",
    "@babel/preset-react": "7.23.7",
    "@babel/preset-typescript": "7.23.7",
    "@types/node": "20.11.0",
    "@types/react": "18.2.48",
    "@types/react-dom": "18.2.18",
    "babel-loader": "9.1.3",
    "clean-webpack-plugin": "4.0.0",
    "html-webpack-plugin": "5.6.0",
    "source-map-loader": "5.0.0",
    "ts-loader": "9.5.1",
    "typescript": "5.3.3",
    "webpack": "5.89.0",
    "webpack-cli": "5.1.4",
    "webpack-dev-server": "4.15.1"
  }
}

2024-07-10 10:20 UTC, Inclet commented on certificate-manager/src/index.tsx
Thank you for sharing your React application entry point. While it's a basic setup, there are several improvements we can make to align with current best practices and enhance type safety.

#### Strengths
- Uses TypeScript for type checking
- Correctly defines App as a functional component

#### Areas for Improvement

1. **ReactDOM Usage**
   - The `ReactDOM.render` method is deprecated in React 18. Use `createRoot` instead.

2. **Type Safety**
   - Add a null check for the root element to prevent potential runtime errors.

3. **Module Imports**
   - Update the React import to include necessary types.

4. **Strict Mode**
   - Consider wrapping your app in React.StrictMode for additional checks.

5. **File Extension**
   - Ensure this file has a `.tsx` extension for TypeScript with JSX.

#### Revised Code

```tsx
import React from 'react';
import { createRoot } from 'react-dom/client';

const App: React.FC = () => {
  return <h1>Hey there champ!! How are you doing?</h1>;
};

const rootElement = document.getElementById('root');
if (!rootElement) throw new Error('Failed to find the root element');

const root = createRoot(rootElement);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

2024-07-10 10:20 UTC, Inclet commented on certificate-manager/tsconfig.json
Thank you for providing the TypeScript configuration. It's a solid starting point, but we can make a few improvements to enhance the development experience and code quality.

#### Suggestions

1. **Add `"outDir"` option**
   - Specify an output directory for compiled files

2. **Include `"rootDir"` option**
   - Define the root directory of source files

3. **Add `"noEmit"` option**
   - Useful when using Babel for transpilation

4. **Consider adding `"baseUrl"` and `"paths"` options**
   - Helps with module resolution and import aliases

5. **Include `"include"` array**
   - Explicitly specify which files to include in compilation

6. **Add more strict checks**
   - Enable additional type-checking flags for better code quality

#### Revised Configuration

```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "jsx": "react",
    "module": "esnext",
    "moduleResolution": "node",
    "lib": ["dom", "esnext"],
    "strict": true,
    "sourceMap": true,
    "target": "esnext",
    "outDir": "./dist",
    "rootDir": "./src",
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    },
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}

2024-07-10 10:20 UTC, Inclet commented on certificate-manager/webpack.config.js
Thank you for sharing your Webpack configuration. It's a good start for a React and TypeScript project, but there are several areas where we can improve and optimize.

#### Strengths
- Uses appropriate plugins (HtmlWebpackPlugin, CleanWebpackPlugin)
- Includes TypeScript and JavaScript loaders
- Sets up a development server with hot reloading

#### Areas for Improvement

1. **Module Rules**
   - The `css-loader` is incorrectly placed in the TypeScript rule
   - Missing style loader for CSS processing

2. **Source Maps**
   - `inline-source-map` is not recommended for production

3. **Output Configuration**
   - Consider using content hashing for better caching

4. **Optimization**
   - No production-specific optimizations are set

5. **Environment Awareness**
   - Configuration doesn't distinguish between development and production environments

6. **TypeScript Integration**
   - Consider using `fork-ts-checker-webpack-plugin` for faster type checking

#### Revised Configuration

```javascript
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

const isDevelopment = process.env.NODE_ENV !== 'production';

module.exports = {
  mode: isDevelopment ? 'development' : 'production',
  entry: './src/index.tsx',
  devtool: isDevelopment ? 'inline-source-map' : 'source-map',
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],
      },
      {
        test: /\.js$/,
        enforce: 'pre',
        use: ['source-map-loader'],
      },
    ],
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
  },
  output: {
    filename: isDevelopment ? '[name].js' : '[name].[contenthash].js',
    path: path.resolve(__dirname, 'dist'),
  },
  devServer: {
    static: {
      directory: path.join(__dirname, 'dist'),
    },
    port: 3000,
    hot: true,
  },
  plugins: [
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      template: './src/index.html',
    }),
    new ForkTsCheckerWebpackPlugin(),
  ],
  optimization: {
    moduleIds: 'deterministic',
    runtimeChunk: 'single',
    splitChunks: {
      cacheGroups: {
        vendor: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendors',
          chunks: 'all',
        },
      },
    },
  },
};

2024-07-10 11:31 UTC, KelliaKamikazi commented
Thank you for the feedback, i am going to thoroughly review all of "the
mentioned" above. Then get back to you.

On Wed, Jul 10, 2024 at 12:20 PM Inclet ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thank you for your work . You've made a good start, but there are several
> areas where we can improve the project structure, configuration, and code
> quality.
> Strengths
>
>    - Basic React and TypeScript setup in place
>    - Webpack configuration included for building the project
>    - Use of important plugins like HtmlWebpackPlugin and
>    CleanWebpackPlugin
>
> Areas for Improvement
>
>    1.
>
>    *Project Structure*
>    - Remove the inner certificate-manager folder. Keep its contents, but
>       move them to the root of your project.
>       - Organize your files into appropriate directories (e.g.,
>       src/components, src/styles, etc.)
>    2.
>
>    *Package.json*
>    - Update dependencies to stable versions
>       - Add scripts for development, production builds, and type checking
>       - Include more project metadata (description, repository, etc.)
>    3.
>
>    *Webpack Configuration*
>    - Separate development and production configurations
>       - Improve module rules for better handling of different file types
>       - Implement better caching strategies and optimizations
>    4.
>
>    *React Code*
>    - Update to use modern React 18 APIs (e.g., createRoot)
>       - Implement proper type checking and null safety
>       - Consider using React.StrictMode
>    5.
>
>    *TypeScript Integration*
>    - Ensure proper TypeScript configuration
>       - Use TypeScript-aware loaders and plugins in Webpack
>    6.
>
>    *Development Experience*
>    - Set up proper source map handling for better debugging
>       - Implement hot module replacement for faster development
>    7.
>
>    *Pull Request Practices*
>    - Remove screenshots of code from PR descriptions. Code should be
>       directly reviewable in the PR.
>       - Use screenshots only for demonstrating UI changes or features.
>
> Key Recommendations
>
>    1. Restructure your project to remove the nested certificate-manager
>    folder.
>    2. Update your package.json with correct versions and additional
>    scripts.
>    3. Refactor your Webpack config to address the issues mentioned.
>    4. Update your React code to use current best practices and APIs.
>    5. Ensure your TypeScript configuration is optimized for your project
>    needs.
>    6. Implement proper error handling and logging.
>    7. For future PRs, include code directly rather than as screenshots.
>    Reserve screenshots for UI demonstrations only.
>
> Next Steps
>
>    1. Address the structural issues by reorganizing your project files.
>    2. Update your configurations based on the feedback provided for
>    package.json and webpack.config.js.
>    3. Refactor your React code entry point as suggested.
>    4. Review and update any other React components in your project to
>    follow best practices.
>    5. Ensure all TypeScript files are properly typed.
>    6. Test your development and build processes to ensure everything
>    works as expected after making these changes.
>
> Your project shows promise, but needs some refinement to align with
> current best practices and to optimize for both development and production
> environments. These changes will significantly improve your project's
> maintainability, performance, and developer experience.
>
> Please feel free to ask if you need any clarification or assistance in
> implementing these suggestions.
> ------------------------------
>
> On certificate-manager/package.json
> <https://github.com/KelliaKamikazi/Certificate-Manager---Kellia/pull/1#discussion_r1671995292>
> :
>
> Thank you for sharing your package.json file. It's a good start for a
> React project with TypeScript and Webpack. Here are some observations and
> suggestions for improvement:
> Strengths
>
>    - Good separation of dependencies and devDependencies
>    - Includes essential React, TypeScript, and Webpack packages
>    - Basic npm scripts for starting and building the project
>
> Suggestions for Improvement
>
>    1.
>
>    *Project Metadata*
>    - Add a meaningful description to the "description" field
>       - Consider adding a "repository" field with your project's
>       repository URL
>    2.
>
>    *Scripts*
>    - Add a "dev" script for development mode (e.g., "dev": "webpack serve
>       --mode development")
>       - Modify the "build" script to use production mode (e.g., "build":
>       "webpack --mode production")
>       - Add a "type-check" script to run TypeScript compiler (e.g., "type-check":
>       "tsc --noEmit")
>    3.
>
>    *Dependencies*
>    - Consider adding @types/node as a devDependency for Node.js types
>    4.
>
>    *Versioning*
>    - Use exact versions for dependencies to ensure consistency (remove ^)
>    5.
>
>    *Package Versions*
>    - Some package versions seem to be ahead of the latest stable releases
>       (e.g., ***@***.***). Double-check if these are the versions you
>       intend to use.
>
> Revised package.json
>
> {
>   "name": "certificate-manager",
>   "version": "1.0.0",
>   "description": "A certificate management application built with React and TypeScript",
>   "main": "index.js",
>   "scripts": {
>     "start": "webpack serve --open",
>     "dev": "webpack serve --mode development",
>     "build": "webpack --mode production",
>     "type-check": "tsc --noEmit",
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "keywords": ["certificate", "management", "react", "typescript"],
>   "author": "Your Name",
>   "license": "ISC",
>   "repository": {
>     "type": "git",
>     "url": "https://github.com/yourusername/certificate-manager.git"
>   },
>   "dependencies": {
>     "react": "18.2.0",
>     "react-dom": "18.2.0"
>   },
>   "devDependencies": {
>     ***@***.***/core": "7.23.7",
>     ***@***.***/preset-env": "7.23.7",
>     ***@***.***/preset-react": "7.23.7",
>     ***@***.***/preset-typescript": "7.23.7",
>     ***@***.***/node": "20.11.0",
>     ***@***.***/react": "18.2.48",
>     ***@***.***/react-dom": "18.2.18",
>     "babel-loader": "9.1.3",
>     "clean-webpack-plugin": "4.0.0",
>     "html-webpack-plugin": "5.6.0",
>     "source-map-loader": "5.0.0",
>     "ts-loader": "9.5.1",
>     "typescript": "5.3.3",
>     "webpack": "5.89.0",
>     "webpack-cli": "5.1.4",
>     "webpack-dev-server": "4.15.1"
>   }
> }
>
> ------------------------------
>
> On certificate-manager/src/index.tsx
> <https://github.com/KelliaKamikazi/Certificate-Manager---Kellia/pull/1#discussion_r1671999013>
> :
>
> Thank you for sharing your React application entry point. While it's a
> basic setup, there are several improvements we can make to align with
> current best practices and enhance type safety.
> Strengths
>
>    - Uses TypeScript for type checking
>    - Correctly defines App as a functional component
>
> Areas for Improvement
>
>    1.
>
>    *ReactDOM Usage*
>    - The ReactDOM.render method is deprecated in React 18. Use createRoot
>       instead.
>    2.
>
>    *Type Safety*
>    - Add a null check for the root element to prevent potential runtime
>       errors.
>    3.
>
>    *Module Imports*
>    - Update the React import to include necessary types.
>    4.
>
>    *Strict Mode*
>    - Consider wrapping your app in React.StrictMode for additional checks.
>    5.
>
>    *File Extension*
>    - Ensure this file has a .tsx extension for TypeScript with JSX.
>
> Revised Code
>
> import React from 'react';import { createRoot } from 'react-dom/client';
> const App: React.FC = () => {
>   return <h1>Hey there champ!! How are you doing?</h1>;};
> const rootElement = document.getElementById('root');if (!rootElement) throw new Error('Failed to find the root element');
> const root = createRoot(rootElement);root.render(
>   <React.StrictMode>
>     <App />
>    [...]

2024-07-18 10:09 UTC, Inclet commented on package.json
> +  "author": "Your Name",
Kindly add your name here. don't leave it with a placeholder!!

2024-07-18 10:10 UTC, Inclet commented on src/index.css
> +    background-color: #f0f0f0;
Hardcoded colors is not a good practice! Kindly, create variables to hold these values.

2024-07-18 10:10 UTC, Inclet commented on src/index.css
> +    color: blue;
Hardcoded colors is not a good practice! Kindly, create variables to hold these values.

2024-07-18 10:11 UTC, Inclet commented on src/index.tsx
> +};
Would you create a separate `App.tsx` file to hold this logic?

Having the entry and the component logic in the file file is not a good practice!

2024-07-18 10:12 UTC, Inclet commented on tsconfig.json
Here's a review of your TypeScript configuration:

#### Strengths
* Comprehensive configuration covering most essential options
* Strict type checking enabled
* Path aliases configured for easier imports
* JSX mode set appropriately for React
* Proper inclusion and exclusion of directories

#### Areas for Consideration
1. **Target and Module**
   * `"target": "ES6"` and `"module": "CommonJS"` might not be optimal for modern web development
2. **Source Map Generation**
   * No configuration for generating source maps
3. **Incremental Compilation**
   * `"incremental"` option not set, which can speed up subsequent builds
4. **Output Directory**
   * No `"outDir"` specified, though `"noEmit": true` suggests no output is intended
5. **Type Checking Strictness**
   * Some additional strict checks could be enabled

#### Recommendations
1. **Update Target and Module**
   * Consider using `"target": "ES2018"` or later, and `"module": "ESNext"` for modern browsers
2. **Enable Source Map Generation**
   * Add `"sourceMap": true` if debugging support is needed
3. **Add Incremental Compilation**
   * Include `"incremental": true` for faster rebuilds
4. **Consider Output Configuration**
   * If output is needed, add `"outDir": "./dist"` and remove `"noEmit": true`
5. **Enhance Type Checking**
   * Consider adding `"noUnusedLocals": true` and `"noUnusedParameters": true`
6. **Improve Module Resolution**
   * Add `"moduleResolution": "node16"` or `"moduleResolution": "bundler"` for better module resolution

#### Improved Configuration
```json
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "ESNext",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node16",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": "./",
    "paths": {
      "@/*": ["src/*"]
    },
    "sourceMap": true,
    "incremental": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}

2024-07-18 10:14 UTC, Inclet requested changes
Kindly review the comment added and address them ASAP!

2024-07-18 11:37 UTC, Inclet commented on src/App.tsx
Here's a review of your implementation:

#### Strengths
* Concise and straightforward component
* Uses arrow function for component definition
* Exports the component as default for easy import

## Areas for Improvement
1. **React Import**
   * The `React` import is unnecessary in newer versions of React (17+)
2. **Component Structure**
   * Single-line component might become hard to maintain as complexity grows

#### Recommendations
1. **Remove Unnecessary React Import**
   * If using React 17+ with the new JSX transform, remove the React import

#### Improved Component:
```tsx
import { FC } from 'react';

const App: FC = () => {
  return (
      <h1>Certificate Manager Application</h1>;
  );
};
};

export default App;

2024-07-18 11:40 UTC, Inclet commented on src/index.tsx
Here's a review of your implementation:

#### Strengths
* Uses the modern `createRoot` API from React 18
* Implements React's Strict Mode for better development practices
* Imports a CSS file for styling
* Uses TypeScript for type assertions

#### Areas for Improvement
1. **Error Handling**
   * No error handling if the root element is not found
2. **React Import**
   * The `React` import is unnecessary in newer versions of React (17+) unless using React.StrictMode
3. **Type Definitions**
   * The type assertion could be more specific (e.g., `HTMLDivElement` instead of `HTMLElement`)
4. **Code Formatting**
   * The import statements and render call could be better formatted for readability
5. **Performance Consideration**
   * No check for production mode to conditionally apply StrictMode

#### Recommendations
1. **Add Error Handling**
   * Implement a check to ensure the root element exists before rendering
2. **Update React Import**
   * Keep only the necessary imports from 'react'
3. **Improve Type Assertion**
   * Use a more specific type for the root element
4. **Enhance Code Formatting**
   * Add line breaks for better readability
5. **Consider Production Mode**
   * Optionally wrap StrictMode based on the environment

#### Improved Code
```tsx
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';

const rootElement = document.getElementById('root');

if (!rootElement) {
  throw new Error('Failed to find the root element');
}

const root = createRoot(rootElement);

root.render(
 process.env.DEV ? (
    <StrictMode>
      <App />
    </StrictMode>
  ) : (
    <App />
  )
);

2024-07-18 11:40 UTC, Inclet commented on src/index.html
Here's a review of your HTML template

#### Strengths
* Proper use of `<!doctype html>` declaration
* Includes `lang` attribute on the `<html>` tag
* Specifies character encoding
* Includes viewport meta tag for responsive design
* Uses `X-UA-Compatible` for better compatibility with older versions of IE
* Provides a title for the application
* Includes a root div for React to render into

#### Areas for Improvement
1. **Favicon**
   * No favicon specified
2. **CSS Classes**
   * HTML tag includes CSS classes, which might be better placed in your CSS files
3. **Noscript Tag**
   * No fallback content for users with JavaScript disabled
5. **Manifest and Icons**
   * No Web App Manifest or Apple Touch Icons specified

#### Recommendations
1. **Include Favicon**
   * Add a link to a favicon for better visual identity in browser tabs
2. **Move CSS Classes**
   * Consider moving CSS classes from the HTML tag to your CSS files
3. **Add Noscript Tag**
   * Include a noscript tag with a message for users with JavaScript disabled
4. **Add Web App Manifest**
   * Include a link to a Web App Manifest file for better PWA support
5. **Include Apple Touch Icons**
   * Add Apple Touch Icons for better iOS support

#### Improved HTML
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Certificate Manager - Manage your certificates efficiently" />
    <title>Certificate Manager</title>
    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>

2024-07-18 11:41 UTC, Inclet requested changes
Kindly check for additional comments added on your PR!

2024-07-19 08:58 UTC, Inclet approved these changes
Great Job!

2024-07-19 08:58 UTC, merged