Feature/task2 kan 30 sidebar and title bar
KelliaKamikazi/Certificate-Manager---Kellia pull request #2
Opened 2024-07-19 12:15 UTC by KelliaKamikazi

#### PR description
- Description of what the PR does

#### Ticket / Jira Link
- [KAN-##](https://task-force-pro-dccs.atlassian.net/jira/software/projects/KAN/boards/1?assignee=712020%3Ab9bb79c7-4352-4d17-9af2-5c36278b1670&selectedIssue=KAN-)

#### Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have created a loom video for the new feature or enhancement
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings 

#### How To Test Changes
- Description of steps to test changes

#### Additional Comments
- Description of more context you want to add

#### Screenshots:
:writing_hand::skin-tone-5:
1
:white_check_mark:
1

2024-07-22 15:29 UTC, Inclet requested changes
Your React components show a solid foundation, but there are areas for improvement:

1. Enhance component structure and organization
2. Improve accessibility features
3. Implement better state management and event handling
4. Use modern React practices and TypeScript features
5. Optimize performance with lazy loading
6. Improve CSS management (consider CSS modules)
7. Enhance error handling and routing

The Express server code seems misplaced in a frontend project. Consider separating backend and frontend concerns for better project organization.

Review the detailed feedback for each component and implement changes incrementally to improve your code quality and maintainability.

2024-07-22 15:29 UTC, Inclet commented on src/App.tsx
#### Strengths
- Uses React Router for navigation
- Implements a clear structure with Header, Sidebar, and main content area
- Uses TypeScript for type safety
- Employs functional component with React.FC type

#### Areas for Improvement

1. **React Import**
   - The React import is unnecessary in newer versions of React (17+)

2. **Route Organization**
   - Routes could be extracted into a separate file for better organization

3. **Lazy Loading**
   - No implementation of lazy loading for route components

4. **Error Handling**
   - Missing error boundary and 404 route

5. **Responsiveness**
   - No apparent handling of sidebar visibility for mobile views

6. **Accessibility**
   - No skip-to-content link for keyboard navigation

7. **CSS Import**
   - Direct import of CSS file might not be ideal for all styling solutions

#### Recommendations

1. Remove unnecessary React import if using React 17+

2. Consider moving routes to a separate file (e.g., `routes.tsx`)

3. Implement lazy loading for route components to improve performance

4. Add an error boundary component and a 404 route

5. Consider adding state management for sidebar visibility on mobile

6. Add a skip-to-content link for better accessibility

7. Consider using CSS modules or a CSS-in-JS solution

#### Improved Code

```tsx
import { FC } from 'react';
import { Route, Routes } from 'react-router-dom';
import Header from './components/Header';
import Sidebar from './components/Sidebar';
import ErrorBoundary from './components/ErrorBoundary';
import NotFound from './components/NotFound';
import Home from './components/Home';
import Example1 from './components/Example1';
import Example2 from './components/Example2';
import Example3 from './components/Example3';
import styles from './App.module.css';

const App: FC = () => {
  return (
    <div className={styles.app}>
      <a href="#main-content" className={styles.skipLink}>Skip to content</a>
      <Header />
      <Sidebar />
      <main id="main-content">
        <ErrorBoundary>
            <Routes>
              <Route path="/" element={<Home />} />
              <Route path="/example1" element={<Example1 />} />
              <Route path="/example2" element={<Example2 />} />
              <Route path="/example3" element={<Example3 />} />
              <Route path="*" element={<NotFound />} />
            </Routes>
          </Suspense>
        </ErrorBoundary>
      </main>
    </div>
  );
};

export default App;

2024-07-22 15:29 UTC, Inclet commented on src/components/Sidebar.tsx
#### Strengths
- Uses React hooks (useState) for managing menu state
- Implements a collapsible submenu
- Uses SVG icons for better scalability

#### Areas for Improvement

1. **Accessibility**
   - Lack of proper ARIA attributes for the expandable menu
   - Missing keyboard navigation support

2. **Component Structure**
   - The component is quite large and could benefit from being broken down into smaller subcomponents

3. **Event Handling**
   - Using stopPropagation() might lead to unexpected behavior

4. **CSS Import**
   - Direct import of CSS file might not be ideal for all styling solutions

5. **Type Safety**
   - No explicit types for the imported SVG files

6. **Naming Conventions**
   - Some variable names could be more descriptive (e.g., 'menuOpen' could be 'isSubmenuOpen')

7. **Comments**
   - Inline comments could be more professional and concise

#### Recommendations

1. Enhance accessibility:
   - Add aria-expanded attribute to the submenu button
   - Implement keyboard navigation for the menu

2. Break down the component:
   - Create separate components for MenuIcon, SubmenuItem, etc.

3. Refactor event handling:
   - Consider using a different approach instead of stopPropagation()

4. Use CSS modules or a CSS-in-JS solution

5. Add proper type definitions for SVG imports

6. Improve naming conventions for better code readability

7. Refine comments to be more professional and concise

#### Improved Structure

```tsx
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import styles from '../styles/Sidebar.module.css';
import { HomeIcon, MenuIcon, AngleDownIcon } from './Icons';
import SubmenuItem from './SubmenuItem';

const Sidebar: React.FC = () => {
  const [isSubmenuOpen, setIsSubmenuOpen] = useState(false);

  const toggleSubmenu = () => setIsSubmenuOpen(!isSubmenuOpen);

  return (
    <nav className={styles.sidebar}>
      <Link to="/" className={styles.startLink}>
        <HomeIcon />
        <span>Start</span>
      </Link>
      <button 
        className={styles.submenuButton} 
        onClick={toggleSubmenu}
        aria-expanded={isSubmenuOpen}
      >
        <MenuIcon />
        <span>Machine Learning</span>
        <AngleDownIcon className={isSubmenuOpen ? styles.rotated : ''} />
      </button>
      {isSubmenuOpen && (
        <ul className={styles.submenu}>
          <SubmenuItem to="/example1" label="Example 1" />
          <SubmenuItem to="/example2" label="Example 2" />
          <SubmenuItem to="/example3" label="Example 3" />
        </ul>
      )}
    </nav>
  );
};

export default Sidebar;

2024-07-22 15:29 UTC, Inclet commented on server.js
This code appears to be a backend server setup using Express, primarily intended to serve a frontend application. However, it's unusual to have this in a frontend codebase. What's you intention here?

2024-07-23 10:24 UTC, AidaLepicDccs requested changes
@Inclet did really good review and I agree with him in all of the comments. In addition to that I just added 2 small things so please check them.

Also please check how app looks on mobile, since this can be better:
![Screenshot 2024-07-23 at 12 23 00](https://github.com/user-attachments/assets/b3338530-c20c-440a-9ccd-b4c4e885e5f3)

- content of page (e.g. 'Example 1') is not completely visible until you make it wide enough

2024-07-23 10:24 UTC, AidaLepicDccs commented on package.json
> +    "@types/react-router-dom": "^6.25.1",
Please fix this dependency version. On building it locally, there is error: 
![Screenshot 2024-07-23 at 12 13 53](https://github.com/user-attachments/assets/fe98ac00-fda9-4606-b4a0-1c8d8aa4c19f)

so please find correct dependency version and use it.

2024-07-23 10:24 UTC, AidaLepicDccs commented on src/components/icons/icons.tsx
> +// import { ReactComponent as MenuIconSvg } from '../styles/items/threelinesmenu.svg?react';
Please remove commented out code since you don't need it and it just makes code not-so-clean.

2024-07-23 12:25 UTC, KelliaKamikazi commented
> @Inclet did really good review and I agree with him in all of the comments. In addition to that I just added 2 small things so please check them.
> 
> Also please check how app looks on mobile, since this can be better: ![Screenshot 2024-07-23 at 12 23 00](https://private-user-images.githubusercontent.com/167890598/351287520-b3338530-c20c-440a-9ccd-b4c4e885e5f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzI1MDgsIm5iZiI6MTcyMTczMjIwOCwicGF0aCI6Ii8xNjc4OTA1OTgvMzUxMjg3NTIwLWIzMzM4NTMwLWMyMGMtNDQwYS05Y2NkLWI0YzRlODg1ZTVmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxMDU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmE3ZmQ5ZTEzNDJkZjVkZDRmOGVjYjIwN2E0ZjkyZjgzZGY1NzAxNWE3MTc1ZWQzZDY3MGI1ZTgwOWQ0ZDBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zbd7_rY8y1tns5JvJFLEO6XDMQPCyxyhS08p5mf9_2U)
> 
> * content of page (e.g. 'Example 1') is not completely visible until you make it wide enough
Below are  pictures of how it looks now 

<img width="430" alt="Screenshot 2024-07-23 at 14 22 32" src="https://github.com/user-attachments/assets/b8137f06-f5a0-4f20-becd-62e77cddf817">

<img width="406" alt="Screenshot 2024-07-23 at 13 38 46" src="https://github.com/user-attachments/assets/5b2a3db0-f9bd-4cbc-ab10-3abe7fa27efb">

For the menu disappearance Issue fix.


<img width="827" alt="Screenshot 2024-07-23 at 14 26 21" src="https://github.com/user-attachments/assets/c00d3be9-b0ef-49bf-b7ae-b7989382f5df">

2024-07-23 13:02 UTC, AidaLepicDccs requested changes

2024-07-23 13:02 UTC, AidaLepicDccs commented on src/components/Sidebar.tsx
> +          onClick={() => setIsSidebarVisible(false)}
You should avoid using lamba functions directly here in callback. You should define these callback as constants wrapping them with 'useCallback' hook to cache them. Or even declare them out of the component. You do not want that browser declare them and initialize each time component re-renders, it's time consuming. Check this article:

https://jonhilton.net/typescript-and-react-forbidden-lambdas/

Please check all places in code where you have it defined like this.

2024-07-23 13:02 UTC, AidaLepicDccs commented on package.json
> +    "serve": "node server.js",
As I understand, you deleted serve.js so please remove it also from here. No leftovers in code.

2024-07-23 13:02 UTC, AidaLepicDccs commented on src/components/Sidebar.tsx
> +  const [isSubmenuOpen, setIsSubmenuOpen] = useState(false);
As we are using Typescript, please make state typed (also all other places should be typed). In this case it should be useState<boolean> to indicate usage of boolean values. Please fix all places where this applies.

2024-07-23 13:58 UTC, AidaLepicDccs approved these changes

2024-07-23 14:23 UTC, merged